-- Vacaciones y relevo
-- ------------------------------------------------------------------
-- Quien se va de vacaciones deja de poder contestar sus encuestas, y hasta aquí
-- la aplicación no lo sabía: al volver le salían vencidas y le bajaban el
-- promedio por semanas en las que no estaba. Con esto cada quien carga sus
-- vacaciones —una o dos semanas completas, de lunes a domingo— y nombra a quien
-- lo releva.
--
--   Quien se va   → las encuestas cuyo periodo cae entero dentro de sus
--                   vacaciones no le cuentan: ni pendiente, ni padrón, ni
--                   promedio, ni certificación. En su lista salen «Relevada».
--   Su relevo     → le aparecen en sus pendientes como «Apoyo por vacaciones»,
--                   y **sí le cuentan**: son una asignación más suya.
--
-- Con semanas completas eso son, en la práctica, las encuestas semanales: una
-- quincena dura 15 o 16 días y dos semanas son 14, así que nunca cabe entera.
-- Lo mensual o más largo se pone al corriente al volver. Las revisiones que le
-- toquen no se relevan: se regularizan al volver.
--
-- Son dos piezas:
--
--   vacaciones                       quién, desde qué lunes, cuántas semanas
--                                    y quién releva.
--   evaluation_responses.relevo_de   en la respuesta que contesta el relevo, a
--                                    quién estaba cubriendo. La respuesta es
--                                    **del relevo** (`employee_id` es el suyo);
--                                    esta columna es lo que la separa de las
--                                    suyas propias.
--
-- Ejecutar en el SQL Editor de Supabase; se puede correr las veces que haga
-- falta. Sin correrlo todo se comporta como antes y el botón de cargar
-- vacaciones dice qué falta.

create table if not exists public.vacaciones (
    id           bigint generated by default as identity primary key,
    employee_id  text not null,
    relevo_id    text,
    desde        date not null,
    semanas      smallint not null default 1 check (semanas between 1 and 2),
    creado_en    timestamptz not null default now(),
    -- Siempre un lunes: son semanas completas, y el periodo de una encuesta
    -- semanal va de lunes a domingo. `isodow` es 1 para el lunes.
    constraint vacaciones_desde_lunes check (extract(isodow from desde) = 1),
    -- Nadie se releva a sí mismo.
    constraint vacaciones_relevo_distinto check (relevo_id is null or relevo_id <> employee_id)
);

create index if not exists vacaciones_empleado on public.vacaciones (employee_id);
create index if not exists vacaciones_relevo on public.vacaciones (relevo_id);

comment on table public.vacaciones is
    'Semanas completas de vacaciones. Lo que cae entero dentro no le cuenta a quien se va y le cuenta a su relevo.';
comment on column public.vacaciones.desde is
    'El lunes en que empiezan. Terminan el domingo de la última semana.';
comment on column public.vacaciones.relevo_id is
    'Quien contesta las encuestas relevadas. Se desliga (null) si se borra su ficha.';

alter table public.evaluation_responses
    add column if not exists relevo_de text;

comment on column public.evaluation_responses.relevo_de is
    'Si la contestó un relevo, a quién cubría. La respuesta cuenta para quien la contestó (employee_id), no para éste.';

alter table public.vacaciones enable row level security;

-- La aplicación no usa el login de Supabase —la sesión vive en localStorage—,
-- así que todo va con la clave `anon`, igual que el resto de las tablas. La
-- lectura es de todos: las estadísticas, el padrón de una encuesta y los
-- pendientes del relevo preguntan por las vacaciones de otros.
drop policy if exists "vacaciones_lectura" on public.vacaciones;
create policy "vacaciones_lectura"
    on public.vacaciones for select
    to anon, authenticated
    using (true);

drop policy if exists "vacaciones_alta" on public.vacaciones;
create policy "vacaciones_alta"
    on public.vacaciones for insert
    to anon, authenticated
    with check (true);

-- El cambio sólo hace falta para desligar al relevo cuando se borra su ficha.
drop policy if exists "vacaciones_cambio" on public.vacaciones;
create policy "vacaciones_cambio"
    on public.vacaciones for update
    to anon, authenticated
    using (true)
    with check (true);

-- Y el borrado es revertirlas, que lo hace quien las cargó.
drop policy if exists "vacaciones_borrado" on public.vacaciones;
create policy "vacaciones_borrado"
    on public.vacaciones for delete
    to anon, authenticated
    using (true);
